import jsPDF from "jspdf";
import type { Meeting } from "../types";

export const exportMeetingPDF = (
  meeting: Meeting,
) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  let y = 20;

  const addFooter = () => {
    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
      "Generated by MeetMind AI",
      20,
      pageHeight - 10,
    );

    doc.text(
      `Page ${doc.getNumberOfPages()}`,
      pageWidth - 30,
      pageHeight - 10,
    );
  };

  const checkPageBreak = (spaceNeeded = 20) => {
    if (y + spaceNeeded > pageHeight - 20) {
      addFooter();
      doc.addPage();
      y = 20;
    }
  };

  const sectionTitle = (title: string) => {
    checkPageBreak();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);

    doc.setTextColor(30);

    doc.text(title, 20, y);

    y += 4;

    doc.setDrawColor(200);
    doc.line(20, y, pageWidth - 20, y);

    y += 8;
  };

  const paragraph = (text: string) => {
    checkPageBreak();

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const lines = doc.splitTextToSize(
      text,
      170,
    );

    lines.forEach((line: string) => {
      checkPageBreak(8);

      doc.text(line, 20, y);

      y += 6;
    });

    y += 4;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);

  doc.text("MeetMind AI", 20, y);

  y += 12;

  doc.setFontSize(17);

  doc.text("Meeting Report", 20, y);

  y += 8;

  doc.setDrawColor(180);

  doc.line(20, y, pageWidth - 20, y);

  y += 12;

  doc.setFontSize(12);

  doc.setFont("helvetica", "bold");
  doc.text("Title:", 20, y);

  doc.setFont("helvetica", "normal");
  doc.text(meeting.title, 45, y);

  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Status:", 20, y);

  doc.setFont("helvetica", "normal");
  doc.text(meeting.status, 45, y);

  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Generated:", 20, y);

  doc.setFont("helvetica", "normal");
  doc.text(
    new Date().toLocaleDateString(),
    45,
    y,
  );

  y += 12;

  sectionTitle("Description");

  paragraph(
    meeting.description ||
      "No description available.",
  );

  sectionTitle("Summary");

  paragraph(
    meeting.summary ||
      "Summary not available.",
  );

  sectionTitle("Key Decisions");

  if (
    meeting.keyDecisions &&
    meeting.keyDecisions.length > 0
  ) {
    meeting.keyDecisions.forEach((decision) => {
      paragraph(
        `• ${decision.task}${
          decision.owner
            ? ` (Owner: ${decision.owner})`
            : ""
        }`,
      );
    });
  } else {
    paragraph("No key decisions available.");
  }

  sectionTitle("Action Items");

  if (
    meeting.actionItems &&
    meeting.actionItems.length > 0
  ) {
    meeting.actionItems.forEach((item) => {
      paragraph(
        `• ${item.task}

Owner: ${
          item.owner || "Not specified"
        }

Deadline: ${
          item.deadline || "Not specified"
        }`,
      );
    });
  } else {
    paragraph("No action items available.");
  }

  sectionTitle("Transcript");

  paragraph(
    meeting.transcript ||
      "Transcript not available.",
  );

  addFooter();

  doc.save(
    `${meeting.title.replace(/\s+/g, "_")}.pdf`,
  );
};